apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kubeloxilb.loxilb.io/v1alpha1",
          "kind": "Kubeloxilbapp",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kube-loxilb-operator",
              "app.kubernetes.io/instance": "kubeloxilbapp-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "kubeloxilbapp",
              "app.kubernetes.io/part-of": "kube-loxilb-operator"
            },
            "name": "kubeloxilbapp-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: kube-loxilb-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kubeloxilbapp is the Schema for the kubeloxilbapps API
      displayName: Kubeloxilbapp
      kind: Kubeloxilbapp
      name: kubeloxilbapps.kubeloxilb.loxilb.io
      version: v1alpha1
  description: k8s operator for kube-loxilb
  displayName: kube-loxilb-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - nodes
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kubeloxilb.loxilb.io
          resources:
          - kubeloxilbapps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kubeloxilb.loxilb.io
          resources:
          - kubeloxilbapps/finalizers
          verbs:
          - update
        - apiGroups:
          - kubeloxilb.loxilb.io
          resources:
          - kubeloxilbapps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kube-loxilb-operator-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - watch
          - list
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - watch
          - list
          - patch
        - apiGroups:
          - ""
          resources:
          - endpoints
          - services
          - services/status
          verbs:
          - get
          - watch
          - list
          - patch
          - update
        - apiGroups:
          - discovery.k8s.io
          resources:
          - endpointslices
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kube-loxilb-operator-kube-loxilb
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: kube-loxilb-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: kube-loxilb-operator
          control-plane: controller-manager
        name: kube-loxilb-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/loxilb-io/kube-loxilb-operator:v0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kube-loxilb-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kube-loxilb-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - loxilb
  - loadbalancer
  links:
  - name: Kube Loxilb Operator
    url: https://kube-loxilb-operator.domain
  maturity: alpha
  provider:
    name: loxilb.io
  version: 0.0.1
