# permissions for end users to edit kubeloxilbapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubeloxilbapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-loxilb-operator
    app.kubernetes.io/part-of: kube-loxilb-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeloxilbapp-editor-role
rules:
- apiGroups:
  - kubeloxilb.loxilb.io
  resources:
  - kubeloxilbapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeloxilb.loxilb.io
  resources:
  - kubeloxilbapps/status
  verbs:
  - get
