---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeloxilb.loxilb.io
  resources:
  - kubeloxilbapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeloxilb.loxilb.io
  resources:
  - kubeloxilbapps/finalizers
  verbs:
  - update
- apiGroups:
  - kubeloxilb.loxilb.io
  resources:
  - kubeloxilbapps/status
  verbs:
  - get
  - patch
  - update
