apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kube-loxilb-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kubeloxilbapp is the Schema for the kubeloxilbapps API
      displayName: Kubeloxilbapp
      kind: Kubeloxilbapp
      name: kubeloxilbapps.kubeloxilb.loxilb.io
      version: v1alpha1
  description: k8s operator for kube-loxilb
  displayName: kube-loxilb-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - loxilb
  - loadbalancer
  links:
  - name: Kube Loxilb Operator
    url: https://kube-loxilb-operator.domain
  maturity: alpha
  provider:
    name: loxilb.io
  version: 0.0.0
