apiVersion: kubeloxilb.loxilb.io/v1alpha1
kind: Kubeloxilbapp
metadata:
  labels:
    app.kubernetes.io/name: kubeloxilbapp
    app.kubernetes.io/instance: kubeloxilbapp-sample
    app.kubernetes.io/part-of: kube-loxilb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-loxilb-operator
  name: kubeloxilbapp-sample
spec:
  # TODO(user): Add fields here
